# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('UA', 'Unassigned'), ('BUG', 'Bug'), ('ENHANCEMENT', 'Enhancement')], default='UA', max_length=15)),
                ('stage', models.CharField(choices=[('DEV', 'Under Development'), ('NOT_STARTED', 'Yet to start developing'), ('DONE', 'Issue resolved in latest build')], default='NOT_STARTED', max_length=50)),
                ('criticality', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('ND', 'Not yet determined')], default='ND', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_use', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbugs.Reporter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbugs.Issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbugs.Reporter'),
        ),
    ]
