# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbugs', '0002_issue_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
